name: Container Image

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU for BuildKit
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker BuildKit
      uses: docker/setup-buildx-action@v2
    - name: Setup Docker Metadata
      uses: docker/metadata-action@v3
      id: docker_meta
      with:
        images: ghcr.io/kendfinger/kosl
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      id: docker_login
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Image
      uses: docker/build-push-action@v2
      id: docker_build_push
      with:
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
